use chrono::{DateTime, NaiveDate, Utc};
use uuid::Uuid;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WebhookFeedItem {
    pub webhook_event_uid: Uuid,
    pub event_timestamp: DateTime<Utc>,
    pub account_holder_uid: Uuid,
    pub content: FeedItem,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WebhookStandingOrderPayment {
    pub webhook_event_uid: Uuid,
    pub event_timestamp: DateTime<Utc>,
    pub account_holder_uid: Uuid,
    pub content: StandingOrderPayment,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WebhookStandingOrder {
    pub webhook_event_uid: Uuid,
    pub event_timestamp: DateTime<Utc>,
    pub account_holder_uid: Uuid,
    pub content: PaymentOrder,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedItem {
    pub feed_item_uid: Uuid,
    pub category_uid: Uuid,
    pub account_uid: Uuid,
    pub amount: CurrencyAndAmount,
    pub source_amount: CurrencyAndAmount,
    pub direction: Direction,
    pub updated_at: DateTime<Utc>,
    pub transaction_time: DateTime<Utc>,
    pub settlement_time: DateTime<Utc>,
    pub source: Source,
    pub source_sub_type: SourceSubtype,
    pub status: Status,
    pub transacting_application_user_uid: Uuid,
    pub counter_party_type: CounterPartyType,
    pub counter_party_uid: Uuid,
    pub counter_party_name: String,
    pub counter_party_sub_entity_uid: Uuid,
    pub counter_party_sub_entity_name: String,
    pub counter_party_sub_entity_identifier: String,
    pub counter_party_sub_entity_sub_identifier: String,
    pub exchange_rate: f64,
    pub total_fee_amount: CurrencyAndAmount,
    pub reference: String,
    pub country: Country,
    pub spending_category: SpendingCategory,
    pub user_note: String,
    pub round_up: AssociatedFeedRoundUp,
    pub has_attachment: bool,
    pub receipt_present: bool,
    pub master_card_feed_details: MasterCardFeedDetails,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StandingOrderPayment {
    pub payment_order: PaymentOrder,
    pub success: bool,
    pub reason: String,
    pub payment_uid: Uuid,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaymentOrder {
    pub payment_order_uid: Uuid,
    pub category_uid: Uuid,
    pub amount: CurrencyAndAmount,
    pub reference: String,
    pub payee_uid: Uuid,
    pub payee_account_uid: Uuid,
    pub payment_order_recurrance: Option<StandingOrderRecurrance>,
    pub processed_immediately: bool,
    pub next_date: NaiveDate,
    pub cancelled_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub spending_category: Option<SpendingCategory>,
    pub standing_order_recurrance: Option<StandingOrderRecurrance>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StandingOrderRecurrance {
    pub start_date: NaiveDate,
    pub frequency: Option<Frequency>,
    pub interval: Option<i32>,
    pub count: Option<i32>,
    pub until_date: NaiveDate,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CurrencyAndAmount {
    pub currency: Currency,
    pub minor_units: i64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssociatedFeedRoundUp {
    pub goal_category_uid: Uuid,
    pub amount: CurrencyAndAmount,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MasterCardFeedDetails {
    pub merchant_identifier: String,
    pub mcc: i32,
    pub pos_timestamp: LocalTime,
    pub authorisation_code: String,
    pub card_last_4: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalTime {
    pub hour: i32,
    pub minute: i32,
    pub second: i32,
    pub nano: i32,
}

#[derive(Debug, Deserialize)]
pub enum Currency {
    NDEFINED,
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BOV,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHE,
    CHF,
    CHW,
    CLF,
    CLP,
    CNY,
    COP,
    COU,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LTL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRO,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MXV,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RUR,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SRD,
    SSP,
    STD,
    STN,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    USN,
    USS,
    UYI,
    UYU,
    UZS,
    VEF,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XBA,
    XBB,
    XBC,
    XBD,
    XCD,
    XDR,
    XOF,
    XPD,
    XPF,
    XPT,
    XSU,
    XTS,
    XUA,
    XXX,
    YER,
    ZAR,
    ZMW,
    ZWL,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Direction {
    In,
    Out,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Source {
    BritishBusinessBankFees,
    CashDeposit,
    CashDepositCharge,
    CashWithdrawal,
    CashWithdrawalCharge,
    Chaps,
    Cheque,
    CicsCheque,
    CurrencyCloud,
    DirectCredit,
    DirectDebit,
    DirectDebitDispute,
    InternalTransfer,
    MasterCard,
    MastercardMoneysend,
    MastercardChargeback,
    FasterPaymentsIn,
    FasterPaymentsOut,
    FasterPaymentsReversal,
    StripeFunding,
    InterestPayment,
    NostroDeposit,
    Overdraft,
    OverdraftInterestWaived,
    FasterPaymentsRefund,
    StarlingPayStripe,
    OnUsPayMe,
    LoanPrincipalPayment,
    LoanRepayment,
    LoanOverpayment,
    LoanLatePayment,
    LoanFeePayment,
    SepaCreditTransfer,
    SepaDirectDebit,
    Target2CustomerPayment,
    FxTransfer,
    IssPayment,
    StarlingPayment,
    SubscriptionCharge,
    OverdraftFee,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SourceSubtype {
    Contactless,
    MagneticStrip,
    ManualKeyEntry,
    ChipAndPin,
    Online,
    Atm,
    CreditAuth,
    ApplePay,
    AndroidPay,
    FitbitPay,
    GarminPay,
    SamsungPay,
    OtherWallet,
    NotApplicable,
    Unknown,
    Deposit,
    Overdraft,
    SettleUp,
    Nearby,
    TransferSameCurrency,
    SctPayment,
    SctRejection,
    SctReturn,
    SctRecall,
    SddPending,
    SddPayment,
    SddReturn,
    CcExchange,
    CcDomestic,
    FxTransferSameAccountHolder,
    FxTransferBetweenAccountHolders,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Status {
    Upcoming,
    Pending,
    Retrying,
    Reversed,
    Settled,
    Declined,
    Refunded,
    AccountCheck,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CounterPartyType {
    Category,
    Cheque,
    Customer,
    Payee,
    Merchant,
    Sender,
    Starling,
    Loan,
}

#[derive(Debug, Deserialize)]
pub enum Country {
    UNDEFINED,
    AC,
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AN,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BU,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CP,
    CR,
    CS,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DG,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EA,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    EU,
    EZ,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    FX,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    IC,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NT,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SF,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SU,
    SV,
    SX,
    SY,
    SZ,
    TA,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TP,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UK,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    XK,
    YE,
    YT,
    YU,
    ZA,
    ZM,
    ZR,
    ZW,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SpendingCategory {
    BillsAndServices,
    Charity,
    EatingOut,
    Entertainment,
    Expenses,
    Family,
    Gambling,
    General,
    Gifts,
    Groceries,
    Holidays,
    Home,
    Income,
    Lifestyle,
    Payments,
    Pets,
    Saving,
    Shopping,
    Transport,
    None,
    Revenue,
    OtherIncome,
    ClientRefunds,
    Inventory,
    Staff,
    Travel,
    Workplace,
    RepairsAndMaintenance,
    Admin,
    Marketing,
    BusinessEntertainment,
    InterestPayments,
    BankCharges,
    Other,
    FoodAndDrink,
    Equipment,
    ProfessionalServices,
    PhoneAndInternet,
    Vehicles,
    DirectorsWages,
    Vat,
    CorporationTax,
    SelfAssessmentTax,
    InvestmentCapital,
    Transfers,
    LoanPrincipal,
    Personal,
    Dividends,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FeedItemFailureReason {
    CardWalletLimit,
    CardApplePayLimit,
    CardPosDisabled,
    CardAtmDisabled,
    CardMobileWalletDisabled,
    CardOnlineDisabled,
    CardGamblingDisabled,
    CardDisabled,
    CardCancelled,
    CardNotActivated,
    CardMagneticStripDisabled,
    CardManualKeyEntryDisabled,
    CardPayAtPumpDeclined,
    CardInsufficientFunds,
    ChildCardMerchantDisabled,
    DestinationAccountInvalid,
    ReferenceInformationIncorrect,
    DestinationAccountCurrencyIncorrect,
    DestinationAccountNameMismatch,
    DestinationAccountUnavailable,
    IncorrectPin,
    IncorrectCvv2,
    InsufficientFunds,
    MandateCancelled,
    MandateNotFound,
    ChequeBeingRepresented,
    ChequeIssuerAccountClosed,
    ChequeNotSignedInAccordanceWithMandate,
    ChequeStopped,
    ChequeDeclinedReferToIssuer,
    LastBillItemCancelled,
    ScaRequired,
    PinTriesExceeded,
    CvcTriesExceeded,
    SuspiciousCardTransaction,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Frequency {
    Daily,
    Weekly,
    Monthly,
    Yearly,
}
